### ISSUE TITLE
Any plans on updating this for the coming semesters ?

### ISSUE THREAD

**Issue by justinjk007** [arilotter/uoitsched#2]
Thanks a bunch

**Comment by ethernet8023** [comment]
I don't maintain this project, but it shouldn't be too hard to fork this & adjust the start date variables :)

**Comment by justinjk007** [comment]
Problem is not the dates, I was able to generate an ics file after some tweaking thou.

**Comment by ethernet8023** [comment]
Feel free to maintain a fork (& i'll add a link in the readme) or submit PRs!

**Comment by justinjk007** [comment]
Welp last when I was trying to get a calendar file generated, the problem was that they had slightly changed the html layout, so I changed the script accordingly. I was waiting till now, so I finish booking all my courses and do a final test before merging, but now they have reverted there changes, so did I. If you play around with the dates you can generate a working ics file now. 


One small problem is Instructor name is lost when parsing, seems to be because of non-standard html stuff, can't seem to help that.
